# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: cmake on macos platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
        bash ./script/build_macos.sh
        tar -czvf core-parser_25.9.3.tar.gz output/aosp/debug/macos/bin/core-parser

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: core-parser_25.9.3_for_macos.tar.gz
        path: core-parser_25.9.3.tar.gz
