name: cmake on macos platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
        bash ./script/build_macos.sh
        VERSION=$(git describe --tags --always)
        tar -czvf core-parser_${VERSION}_macos.tar.gz output/aosp/debug/macos/bin/core-parser

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: core-parser_macos
        path: core-parser_*_macos.tar.gz
