name: release on macos platforms

on:
  push:
    tags: [ "v*" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
        bash ./script/build.sh
        tar -czvf core-parser_${GITHUB_REF_NAME}_macos.tar.gz output/aosp/release/linux/bin/core-parser

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: core-parser_${GITHUB_REF_NAME}_macos.tar.gz
